### PR TITLE
address Pranav & Vighnesh comments

### PR DESCRIPTION
**Pull request by sblunt**

### CODE REVIEW

**Comment by sblunt** [comment]
@vighnesh-nagpal @pranav-satheesh let me know what you think!

**Comment by vighnesh-nagpal** [comment]
Your comments sound good! With regards to random sampling, in addition to quickly mentioning it during the live session, it might be good to link a video explaining the concept.

**Comment by pranav-satheesh** [comment]
The changes look good 👍🏽

**Comment by sblunt** [comment]
Great suggestion @vighnesh-nagpal-- I just added another sentence explanation and linked a fun video on random sampling.

**Pull request merged**
