### PR TITLE
Update INSTALL_WINDOWS.md

### PR DESCRIPTION
**Pull request by physical256**
Added a note to the windows instructions discussing the new native support for Linux GUI apps with a link to the Microsoft tutorial (that contains preview drivers for intel AMD and NVidia GPU).

### CODE REVIEW

**Comment by physical256** [comment]
Updated win11 native support section to mention it is specifically for wsl2

**Comment by semaphoreP** [comment]
Thanks for adding this. Maybe let's move it to the top of the xming section? Basically, telling people if they are running WSL2 on Windows 11, they probably can skip the following xming install unless graphics aren't working for them out of the box. How's that sound?

**Comment by physical256** [comment]
Yep will do

**Comment by physical256** [comment]
Moved ahead of xming install and added like about skipping xming if you met the build criteria

**Pull request merged**
